### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by jychenger** [jychenger/msfkaux#1]
└`Arch Linux  Python3.9.2`
[~/github/msfkaux]> python msfkaux.py
请输入最终下载链接
下载文件链接https://highlightjs.org/download/
filename:hiagco.zip
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/github/msfkaux/msfkaux.py", line 112, in <module>
    download(url, file_name)
  File "/data/data/com.termux/files/home/github/msfkaux/msfkaux.py", line 93, in download
    each_size = min(each_size, file_size)
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by jychenger** [comment]
这是爬虫下载网络不稳定造成的，可以添加一个`try:...   except:...    else:...`模块
